### ISSUE TITLE
播放失败

### ISSUE THREAD

**Issue by PureCo2Fe** [zhaozy0308/32Zeta#4]
![image](https://user-images.githubusercontent.com/112563773/194693781-f4af5bb5-97cb-4a2e-82ca-b5ab605b5fa2.png)

**Comment by PureCo2Fe** [comment]
/play https://youtube.com/watch?v=DNmtYLhoAcQ
之后没有声音，求大佬解救

**Comment by PureCo2Fe** [comment]
修好了
```
apt-get install libopus0
pip install opuslib
```

**Comment by 31Zeta** [comment]
哇十分感谢补充，没想到真的有人会来用
现在还是一堆BUG经常报错，但是基础的功能还是能用的
有什么问题可以再问我，我试试能不能解决，有的我也得现场研究哈哈

**Comment by PureCo2Fe** [comment]
> 哇十分感谢补充，没想到真的有人会来用
> 现在还是一堆BUG经常报错，但是基础的功能还是能用的
> 有什么问题可以再问我，我试试能不能解决，有的我也得现场研究哈哈

不过也太感谢大佬了，dc最近ban了一些公共robot，都播不了了

我看github上，那些dc-bilibili的项目都没人维护，填好一大堆设置之后，一安装一大堆bug，安装好又完全没有反应，心态属实崩了

支持大佬的无私付出，已star
