### ISSUE TITLE
无法正确读取Youtube电台Playlist

### ISSUE THREAD

**Issue by PureCo2Fe** [zhaozy0308/32Zeta#5]
例如以下链接，Bot会读取到300多首歌曲，但是打开Youtube的话，只会有25首歌
https://www.youtube.com/watch?v=MxHx8Ee2NW0&list=RDAMVM-3p2EM3y9CQ&index=1

**Comment by PureCo2Fe** [comment]
短暂的补救方法：修改 `ytb_dl.py` 文件
```
def ytb_get_info(ytb_url):
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': "./downloads/" + '/%(title)s.%(ext)s',
    }
```
改为
```
def ytb_get_info(ytb_url):
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': "./downloads/" + '/%(title)s.%(ext)s',
        'playliststart': 1,
        'playlistend': 25,
    }
```
<strike>（算是能用吧，应该没有人会把超长的playlist放在dc播吧） </strike>

**Comment by 31Zeta** [comment]
还有其他的链接有这样的问题吗，可能是下载视频的api的问题，我还需要再观察观察

**Comment by 31Zeta** [comment]
我刚看了一下，这个链接指向的是一个合辑而不是一个播放列表。这个合辑应该是右边同时只显示25个视频，你点了后面的视频后合辑接下来的视频就会出现了（在最下面，往后点几个视频下面就会多出几个），所以应该确实是有300多首。读取过大的列表加载过长的问题我再看看怎么解决，后面可能会换api。
