### ISSUE TITLE
youtube短網址無法匹配

### ISSUE THREAD

**Issue by Yswag** [zhaozy0308/32Zeta#6]
你好，/play link:時輸入youtube短網址沒辦法識別成url，會拿url去youtube搜索。例如這個網址：https://youtu.be/4dB0bo6doM4
![image](https://github.com/31Zeta/Zeta-DiscordBot/assets/91155348/a0c260f9-78ba-4a95-bd31-db339b02a31f)

**Comment by 31Zeta** [comment]
刚刚更新添加支持了，用新的v0.8.4试试看

**Comment by Yswag** [comment]
> 刚刚更新添加支持了，用新的v0.8.4试试看

更新完可以正常識別了，感謝！
